class DAssets:
    class Sprites:
        # HERO
        mage = 'assets/sprites/mage.png'
        rogue = 'assets/sprites/rogue.png'
        warrior = 'assets/sprites/warrior.png'
        huntress = 'assets/sprites/huntress.png'

        # Other
        amulet = 'assets/sprites/amulet.png'
        avatars = 'assets/sprites/avatars.png'
        bat = 'assets/sprites/bat.png'
        bee = 'assets/sprites/bee.png'
        blacksmith = 'assets/sprites/blacksmith.png'
        brute = 'assets/sprites/brute.png'
        crab = 'assets/sprites/crab.png'
        demon = 'assets/sprites/demon.png'
        dm100 = 'assets/sprites/dm100.png'
        dm200 = 'assets/sprites/dm200.png'
        dm300 = 'assets/sprites/dm300.png'
        elemental = 'assets/sprites/elemental.png'
        eye = 'assets/sprites/eye.png'
        ghost = 'assets/sprites/ghost.png'
        ghoul = 'assets/sprites/ghoul.png'
        gnoll = 'assets/sprites/gnoll.png'
        golem = 'assets/sprites/golem.png'
        goo = 'assets/sprites/goo.png'
        guard = 'assets/sprites/guard.png'
        guardian = 'assets/sprites/guardian.png'
        item_icons = 'assets/sprites/item_icons.png'
        items = 'assets/sprites/items.png'
        king = 'assets/sprites/king.png'
        larva = 'assets/sprites/larva.png'
        lotus = 'assets/sprites/lotus.png'
        mimic = 'assets/sprites/mimic.png'
        monk = 'assets/sprites/monk.png'
        necromancer = 'assets/sprites/necromancer.png'
        ninja_log = 'assets/sprites/ninja_log.png'
        pet = 'assets/sprites/pet.png'
        piranha = 'assets/sprites/piranha.png'
        pylon = 'assets/sprites/pylon.png'
        rat = 'assets/sprites/rat.png'
        ratking = 'assets/sprites/ratking.png'
        red_sentry = 'assets/sprites/red_sentry.png'
        ripper = 'assets/sprites/ripper.png'
        rot_heart = 'assets/sprites/rot_heart.png'
        rot_lasher = 'assets/sprites/rot_lasher.png'
        scorpio = 'assets/sprites/scorpio.png'
        shaman = 'assets/sprites/shaman.png'
        sheep = 'assets/sprites/sheep.png'
        shopkeeper = 'assets/sprites/shopkeeper.png'
        skeleton = 'assets/sprites/skeleton.png'
        slime = 'assets/sprites/slime.png'
        snake = 'assets/sprites/snake.png'
        spawner = 'assets/sprites/spawner.png'
        spinner = 'assets/sprites/spinner.png'
        spirit_hawk = 'assets/sprites/spirit_hawk.png'
        statue = 'assets/sprites/statue.png'
        succubus = 'assets/sprites/succubus.png'
        swarm = 'assets/sprites/swarm.png'
        tengu = 'assets/sprites/tengu.png'
        thief = 'assets/sprites/thief.png'
        undead = 'assets/sprites/undead.png'
        wandmaker = 'assets/sprites/wandmaker.png'
        wards = 'assets/sprites/wards.png'
        warlock = 'assets/sprites/warlock.png'
        wraith = 'assets/sprites/wraith.png'
        yog = 'assets/sprites/yog.png'
        yog_fists = 'assets/sprites/yog_fists.png'

    class Environment:
        """16x16"""
        tiles_sewers = 'assets/environment/tiles_sewers.png'
        tiles_prison = 'assets/environment/tiles_prison.png'
        tiles_caves = 'assets/environment/tiles_caves.png'
        tiles_city = 'assets/environment/tiles_city.png'
        tiles_halls = 'assets/environment/tiles_halls.png'

    class Terrain:
        features = 'assets/environment/terrain_features.png'

    class Water:
        water0 = 'assets/environment/water0.png'
        water1 = 'assets/environment/water1.png'
        water2 = 'assets/environment/water2.png'
        water3 = 'assets/environment/water3.png'
        water4 = 'assets/environment/water4.png'
